/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package transportation;

import org.junit.Test;
import static org.junit.Assert.*;

public class TransportationTest {

    /**
     * Passing a null truck into method transport
     */
    @Test(expected = IllegalArgumentException.class)
    public void testTransportByGivingANullTruck() {
        Transportation session = new Transportation();
        session.transport(null, 3);
    }

    /**
     * Passing a negative cargo weight into method transport
     */
    @Test(expected = IllegalArgumentException.class)
    public void testTransportByGivingANegativeCargoWeight() {
        Transportation session = new Transportation();
        Truck truck = new Truck();
        session.transport(truck, -3);
    }

    /**
     * Passing a cargo weight which is higher than the max support weight of a truck
     */
    @Test
    public void testTransportByGivingAHeavyCargoWeight() {
        Transportation session = new Transportation();
        Truck truck = new Truck();
        int status = session.transport(truck, 3);
        assertEquals(-1, status);
    }

    /**
     * Passing all valid params
     */
    @Test
    public void testTransportByGivingAllValidParams() {
        Transportation session = new Transportation();
        Truck truck = new Truck();
        int status = session.transport(truck, 2);
        assertEquals(0, status);
    }

}
